-- AlterTable
ALTER TABLE `user` ADD COLUMN `allowDeviceRecovery` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `allowEmailRecovery` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `allowPhoneRecovery` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `allowQRLogin` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `allowRecoveryPhrase` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `appliedGiftCodes` TEXT NULL,
    ADD COLUMN `credits` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `emergencyContacts` TEXT NULL,
    ADD COLUMN `preferences` TEXT NULL,
    ADD COLUMN `recoveryEmail` VARCHAR(191) NULL,
    ADD COLUMN `recoveryFileHash` VARCHAR(191) NULL,
    ADD COLUMN `recoveryPhone` VARCHAR(191) NULL,
    ADD COLUMN `recoveryPhoneCountryCode` VARCHAR(191) NULL,
    ADD COLUMN `recoveryPhrase` TEXT NULL,
    ADD COLUMN `twoFactorEnabled` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `twoFactorMethod` VARCHAR(191) NULL,
    ADD COLUMN `twoFactorSecret` TEXT NULL,
    ADD COLUMN `twoPasswordMode` BOOLEAN NOT NULL DEFAULT false;
