-- AlterTable
ALTER TABLE `emailaccount` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `storageUsed` DOUBLE NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `plan` ADD COLUMN `features` VARCHAR(191) NULL,
    ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `maxDomains` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `maxStorageGB` INTEGER NOT NULL DEFAULT 1,
    MODIFY `maxEmails` INTEGER NOT NULL DEFAULT 1;
